#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Installation methods;
#  For python, consider pymarkdown
#  brew install markdownlint-cli
#  (Ubuntu)
#   ensure nodejs >= 18 if not:
#     curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
#   otherwise:
#     sudo apt install nodejs npm
#   sudo npm install -g markdownlint-cli
# project config file: .markdownlint.yaml
# sample: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# plugin_cmd="markdownlint"
# If used on the whole project
proj_plugin_cmd="markdownlint ."

# file extensions this plugin handles
plugin_extensions=(
    .md
)
