#!/bin/bash
# shellcheck disable=SC2034

# Installation methods;
#  pip install yamllint   # can be installed on iSH
#  brew install yamllint
#  (Ubuntu) sudo apt install yamllint
#  (Alpine) sudo apk add yamllint

# project config files: .yamllint
#  ---
#  extends: default
#  rules:
#    line-length:
#    max: 92
#    level: warning

# plugin_cmd="yamllint -s" # -s trigger error on warnings
# If used on the whole project
proj_plugin_cmd="yamllint -s ."

# file extensions this plugin handles
plugin_extensions=(
    .yml
)

# file-types this plugin handles
plugin_file_types=(
)
