# Dummy tmux conf - can be softlinked from ~/.tmux.conf to have a consistent test scenario

# Remove the default prefix, do it before assigning
# the selected one, in case it was some variant of C-b
unbind  C-b
set -g prefix C-a
bind -N "Repeats sends C-a through"  C-a  send-prefix
bind -N "prefix then same char sends C-a through"  a  send-keys C-a


#
# Works for >= 3.4
#
# Ms modifies OSC52 clipboard handling to work with mosh
set -g -a terminal-overrides ",*:Ms=\\E]52;c%p1%.0s;%p2%s\\7"
set -g set-clipboard on

# according to tmux wiki this should work for 3.2 and up
# set -as terminal-features ',*:clipboard'
