#!/bin/sh

CURRENT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

sudo cp -av "$CURRENT_DIR"/tools/myt /usr/local/bin

#
#  Rt is used via  https://github.com/jaclu/helpfull_scripts.git
#
#sudo cp -av "$CURRENT_DIR"/tools/rt /usr/local/bin
