#!/bin/bash
#  This is sourced. Fake bang-path to help editors and linters
#  shellcheck disable=SC2034  # don't warn about unused variables

# Installation methods;
#  pip3 install bashate  # usable on iSH
#  brew install bashate
#  (Ubuntu) sudo apt install python3-bashate

# bashate doesn't have a config file, so I created one!
# and included bashate-wrapper. This is called by olint to first parse
# this config then run bashate
# project config file: .bashateconfig
#  max-line-length=92
#  ignore=E001,E002

plugin_cmd="bashate"

if command -v "$plugin_cmd" >/dev/null; then
    if command -v bashate-wrapper >/dev/null; then
        # this reads .bashateconfig
        plugin_cmd="bashate-wrapper"
    fi
fi

# much faster than shellcheck, but in a few corner cases will fail to
# give a meaningful error. such as missing a } somewhere will just
# be reported as unexpected end of file.
# so better to run after shellcheck
plugin_priority=40

#  file-types this plugin handles
plugin_file_types=(
    "Bourne-Again shell script*"
    "Paul Falstad's zsh script"
)

plugin_extensions=(
    .bash
)
