#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

#
# Provided by flake8, don't use this if flake8 is used!
#

# Installation methods;
#  pip install pycodestyle  # usable on iSH
#  brew install pycodestyle
#  (Ubuntu) sudo apt install pycodestyle
#  (Alpine) sudo apk add py3-pycodestyle

# inline-excludes:  # noqa: E402
# project config files: setup.cfg
#  [pycodestyle]
#  max-line-length = 92

if [[ -n "$(command -v flake8)" ]]; then
    #
    # Redundant if flake8 is found, this is part of flake8
    # set to /dev/null instead of "" to avoid warning
    #   missing: plugin_cmd
    #
    plugin_cmd="/dev/null"
else
    plugin_cmd="pycodestyle"
    # If used on the whole project
    # proj_plugin_cmd="pycodestyle ."
fi

plugin_priority=78

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
