#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

#
# Provided by flake8, don't use this if flake8 is used!
#

# Installation methods;
#  pip install pyflakes  # usable on iSH

#  (Ubuntu) sudo apt install pyflakes3
#  (Alpine) sudo apk add py3-pyflakes

# inline-excludes:  # noqa: F401,F403

if [[ -n "$(command -v flake8)" ]]; then
    #
    # Redundant if flake8 is found, this is part of flake8
    # set to /dev/null instead of "" to avoid warning
    #   missing: plugin_cmd
    #
    plugin_cmd="/dev/null"
else
    # obviously there are two names it might use...
    if [[ -n "$(command -v pyflakes3)" ]]; then
        _cmd="pyflakes3"
    else
        _cmd="pyflakes"
    fi
    plugin_cmd="$_cmd"
    # If used on the whole project
    # proj_plugin_cmd="$_cmd ."
fi

plugin_priority=80

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
