#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

#
#  Special case for checking .pylintrc files, fairly limmited
#  functionality, only finds some error...
#
plugin_cmd="pylint --help"

# file extensions this plugin handles
plugin_extensions=(
    .pylintrc
)
