#!/bin/sh
#
#  Copyright (c) 2022-2025: Jacob.Lundqvist@gmail.com
#  License: MIT
#
#  Part of https://github.com/jaclu/my_tmux_conf
#
#  Auto-generates new tmux conf and starts/attaches tmux
#  Unless it is already running with a different version of tmux.
#  In such cases a warning is displayed and a pause of 5 seconds is done,
#  after which attach is attempted without replacing the tmux conf.
#
#
#  This needs the python module tmux_conf, and by default it will create
#  its own venv installing this if not found, or of an incompatible version.
#
#  If you don't need to use a venv for the python that compiles your tmux conf,
#  do: touch $HOME/.myt_skip_venv
#

#---------------------------------------------------------------
#
#   notifications
#
#---------------------------------------------------------------

display_help() {
    #region help text
    cat <<EOF
Usage: myt [-c tmux] [-m] [-q] [-s] [-2] [profile]

Generates config and starts tmux
Default profile is hostname.py
Options can be given in any order.

Available options:

-h       Print this help and exit.
-c       Use this tmux binary (default tmux)
-m       Use tmate
-q       Dont generate config, start tmux directly
-s       Share session
--venv   (Re-) Create venv for building tmux.conf
-2       Run in T2_ENV (inner tmux, other prefix)
profile  Run using specific profile
EOF
    #endregion
    exit 0
}

log_it() {
    echo "$1"
    [ -n "$myt_log" ] && {
        echo "[$(date '+%F %T')] $1" >>"$myt_log" || {
            echo "ERROR: Failed to log output to: $myt_log" >/dev/stderr
            exit 3
        }
    }
}

error_msg() {
    echo
    log_it "ERROR: $1"
    ex_code="${2:-1}"
    [ "$ex_code" -ge 0 ] && exit "$ex_code"
}

run_cmd() {
    # Used to run a command, log output and report exit code of operation
    _c="$(eval "$1")"
    ex_code="$?"
    echo
    log_it "$_c"
    echo
    return "$ex_code"
}

is_fs_chrooted() {
    # cmdline check:
    # grep -qv " / / " /proc/self/mountinfo || echo "is chrooted"

    # this quick and simple check doesn't work on ish
    # so lets pretend for now chroot does not happen on ish
    [ -d /proc/ish ] && return 1

    [ "$(uname -s)" != "Linux" ] && return 1 # can only chroot this on Linux
    ! grep -q " / / " /proc/self/mountinfo
}

#---------------------------------------------------------------
#
#   venv handling
#
#---------------------------------------------------------------

py_venv_create() {
    [ -d "$d_venv" ] && {
        log_it "---  Removing previous venv: $d_venv"
        rm -rf "$d_venv"
    }
    log_it "---  Creating py venv: $d_venv"
    echo
    echo "If this seems to take forever, run: $my_tmux_conf_location/tools/progress-venv-build.sh"
    echo "in a separate terminal to see progress"
    echo
    python3 -m venv "$d_venv"
    #  shellcheck source=/dev/null
    . "$d_venv"/bin/activate || error_msg "Failure to activate new venv"
    log_it " --  Using py venv: $d_venv"
    log_it " --  pip install -U pip"
    pip install -U pip

    #  Python dependency
    log_it " --  pip install tmux_conf"
    pip install tmux_conf || error_msg "Failure in: pip install tmux_conf"
    log_it "---  Created venv: $d_venv"
    echo # on screen spacer
}

py_venv_activate() {
    #
    #  Activate Python venv, will only be called if use_python_venv ia true
    #
    if [ -f "$scr_venv_activate" ]; then
        log_it " --  Using py venv: $d_venv"
        #  shellcheck source=/dev/null
        . "$scr_venv_activate"
    else
        log_it "---  Not found: $scr_venv_activate - (re-)creating venv..."
        py_venv_create
    fi
    log_it " Using Python: $(command -v python3)"
}

py_venv_deactivate() {
    #
    #  Deactivate Python venv, will only be called if use_python_venv ia true
    #
    log_it " --  Exiting py venv: $d_venv"
    deactivate
}

#---------------------------------------------------------------
#
#   running tmux
#
#---------------------------------------------------------------

select_tmux_bin() {
    # log_it "><> select_tmux_bin()"
    #
    #  Selects what tmux bin to use
    #
    TMUX_BIN=""
    if $tmate_mode; then
        if command -v tmate >/dev/null; then
            TMUX_BIN="tmate"
            # log_it "><> tmate mode - TMUX_BIN=tmate"
            return
        else
            error_msg "tmate not found"
        fi
    fi
    if [ -n "$tmux_bin" ]; then
        # User defined tmux
        TMUX_BIN="$tmux_bin"
        # log_it "><> user defined tmux: $TMUX_BIN"
        unset tmux_bin
        return
    fi
    asdf_scan && return
    TMUX_BIN="$(command -v tmux)"
    if [ -n "$TMUX_BIN" ]; then
        # log_it "><> tmux found in PATH: $TMUX_BIN"
        return
    fi
    [ -z "$TMUX_BIN" ] && error_msg "no tmux in PATH!"
}

asdf_scan() {
    # if asdf is used expand the shim into the actual tmux  bin
    [ ! -x "${ASDF_DATA_DIR:-$HOME/.asdf}/shims/tmux" ] && {
        # asdf tmux not installed
        return 1
    }
    TMUX_BIN="$(asdf which tmux 2>/dev/null)"
    [ -n "$TMUX_BIN" ] && {
        # log_it "><> asdf defined tmux: $TMUX_BIN"
        return 0
    }
    error_msg "asdf with tmux defined, but 'asdf which tmux' failed to report path"
}

define_tmux_env() {
    # log_it "><> define_tmux_env()"
    select_tmux_bin
    #
    #  To not collide when checking for colliding versions
    #  add a prefix for chrooted envs, in order for socket
    #  names not to potentially collide with what is running
    #  on the host
    #
    tmux_vers="$($TMUX_BIN -V | cut -d ' ' -f 2)"

    socket="$(id -u)"
    $tmate_mode && socket="$socket-tmate"
    is_fs_chrooted && socket="${socket}-chr"
    if $t2_env; then
        socket="$socket"-serv2
        if $tmate_mode; then
            conf_file="$HOME/t2/tmate.conf"
        else
            conf_file="$HOME/t2/tmux/tmux.conf"
        fi
        #
        #  Handle some odd long versions, since they will be displayed in
        #  status bar on t2 envs
        #
        case "$tmux_vers" in
        3.1-rc) tmux_vers="3.1" ;; # asdf tmux 3.1 reports as this

        next-3.4)
            #  shellcheck disable=SC2034 # TODO: check why this is alerting
            tmux_vers="3.4"
            ;; # Alpine 3.18 reports as this
        *) ;;
        esac
    else
        socket="$socket"-default
        if $tmate_mode; then
            conf_file="$HOME/.tmate.conf"
        else
            conf_file="$HOME/.tmux.conf"
        fi
    fi
    # log_it "><>   tmux_vers [$tmux_vers]"
    chk_incompatible_socket
}

chk_incompatible_socket() {
    # log_it "><> chk_incompatible_socket()"
    #
    #  Ensure tmux socket is not used by another running version of tmux
    #
    socket_identifier=" -L $socket "

    #
    # verssion will just be mentioned in the path if it is a asdf tmux or similar
    # so the typical basic paths are excluded from this check
    #
    # ps ax | grep "$socket_identifier" | grep -qv -e /usr/bin/tmux -e /usr/local/bin/tmux -e "$tmux_vers" -e grep && {
    #
    #  shellcheck disable=SC2009
    #ps ax | grep "$socket_identifier" | grep -i asdf | grep -v -e "$tmux_vers" -e grep && {
    other_versions_running="$(ps ax | grep "$socket_identifier" | grep -v -e " $TMUX_BIN" -e grep -e real/tmux)"
    if [ -n "$other_versions_running" ]; then
        #  shellcheck disable=SC2009
        log_it "
WARNING: It seems instances for version other than $tmux_vers are using socket: $socket

Intended to use: $TMUX_BIN

Found the following processes:

$other_versions_running

This might not work well, depending on how much the versions differ.
This tmux will start in five seconds - Press Ctrl-C to abort"
        sleep 5
        #else
        #log_it "><> no other tmux versions running on this socket"
    fi
    unset other_versions_running
}

not_source_asdf_if_found() {
    # try each param, and source the first found in the FS
    while [ -n "$1" ]; do
        if [ -f "$1" ]; then
            # ASDF_DIR="$(dirname "$(realpath "$1")")"
            #  shellcheck source=/dev/null
            . "$1"
            return 0 # true
        fi
        shift
    done
    return 1 # false
}

indicate_tmux_connection_type() {
    # log_it "><> indicate_tmux_connection_type()"
    connect_type="$1"
    [ -z "$connect_type" ] && {
        error_msg "indicate_tmux_connection_type() - no param1"
    }
    log_it "$connect_type using: $TMUX_BIN [$tmux_vers]"
    log_it "    socket: $socket - config: $conf_file"
}

is_tmux_ses_running() {
    # log_it "><> is_tmux_ses_running()"
    if $TMUX_BIN -L "$socket" list-sessions >/dev/null 2>&1; then
        # log_it "><> found sessions"
        return 0
    else
        # log_it "><> no sessions"
        return 1
    fi
}

is_tmux_cli_connected() {
    # log_it "><> is_tmux_cli_connected() $TMUX_BIN"
    if [ -n "$($TMUX_BIN -L "$socket" list-clients)" ]; then
        # log_it "><> was connected"
        return 0
    else
        # log_it "><> nothing connected"
        return 1
    fi
}

drop_other_clients() {
    # log_it "><> drop_other_clients()"
    # disconnect any other clients
    is_tmux_cli_connected && {
        # log_it "><> doing detach"
        #
        #  tmux -d just kills other clients using the same session
        #  this kills all other clients regardless of session
        #
        log_it "Detaching other clients currently using:"
        log_it "    $TMUX_BIN [$tmux_vers]"
        log_it "    socket: $socket"
        $TMUX_BIN -L "$socket" list-clients | cut -d: -f 1 |
            xargs -I{} "$TMUX_BIN" -L "$socket" detach-client -t {}
    }
    # log_it "><> detach done"
}

ensure_cfg_file_present() {
    # log_it "><> ensure_cfg_file_present()"
    if [ -f "$conf_file" ]; then
        log_it "Using existing config file"
    else
        log_it "Conf file not found: $conf_file"
        log_it "Creating empty one to prevent 'No such file or directory' error"
        touch "$conf_file"
    fi
}

start_tmux() {
    # log_it "><> start_tmux()"
    if [ -z "$profile" ] && ! find_host_profile; then
        log_it "*** Warning: no profile found"
        sleep 3
        profile="$my_tmux_conf_location/default_plugins.py"
    fi

    define_tmux_env

    # ensure socket is not used inside itself
    # shellcheck disable=SC2154
    [ -n "$TMUX" ] && {
        # shellcheck disable=SC2154
        if echo "$TMUX" | grep -q "$socket" ||
            echo "$TMUX_OUTER" | grep -q "$socket"; then

            error_msg "Attempt to start 'tmux $conf_file' from within itself"
        fi
        export TMUX_OUTER="$TMUX"
    }

    if $quick_mode; then
        # log_it "><> quick mode ensure config file is there"
        ensure_cfg_file_present
    else
        create_tmux_conf
    fi

    cd "$d_initial" || error_msg "Failed to cd back to [$d_initial]"

    # really old tmux'es < 1.4 complain if TMUX is set,
    # even if it is using a different socket
    unset TMUX

    if is_tmux_ses_running; then
        $single_session && drop_other_clients
        indicate_tmux_connection_type "Attaching to"
        tmux_params="attach-session -t main"
    else
        indicate_tmux_connection_type "Starting"
        tmux_params="new-session -s main"
    fi
    run_cmd "$TMUX_BIN -L $socket -f $conf_file $tmux_params"
    [ "$ex_code" != 0 ] && error_msg "tmux exit code: $ex_code"
}

#---------------------------------------------------------------
#
#   Setup tmux env
#
#---------------------------------------------------------------

get_my_tmux_conf_location() {
    # log_it "><> get_my_tmux_conf_location()"
    #  where  my_tmux_conf is located
    f_destination="$HOME"/.config/my_tmux_conf_location
    [ ! -f "$f_destination" ] && {
        log_it "Location of my_tmux_conf repo not stored, go to repo folder"
        log_it "and run ./deploy to solve his"
        exit 1
    }

    my_tmux_conf_location="$(cat "$f_destination")"
    [ ! -d "$my_tmux_conf_location" ] && {
        log_it "Location of my_tmux_conf repo incorrect, go to repo folder"
        log_it "and run ./deploy to solve his"
        exit 1
    }
    d_venv="$my_tmux_conf_location"/.venv
    scr_venv_activate="$d_venv"/bin/activate
}

create_tmux_conf() {
    log_it "create_tmux_conf()"
    #
    #  Generate a new tmux conf file
    #
    cd "$my_tmux_conf_location" || error_msg "Failed to cd into: $my_tmux_conf_location"

    log_it " Using tmux: $TMUX_BIN [$tmux_vers]"
    if $use_python_venv; then
        py_venv_activate || error_msg "Failed to activate venv - run: myt --venv"
    else
        log_it " Using Python: $(command -v python3)"
    fi

    cmd="$profile -r -t $TMUX_BIN $conf_file"
    if $t2_env; then
        cmd="T2_ENV=1 $cmd"
    fi

    run_cmd "$cmd"
    $use_python_venv && [ "$ex_code" = 23 ] && {
        # incorrect version of tmux-conf pip found, try only once to recreate the venv
        # to avoid a potential infinite loop
        log_it "=====   trying to recreate venv   ====="

        py_venv_deactivate
        rm -f "$scr_venv_activate"
        py_venv_activate || {
            error_msg "Failed to recreate & activate venv - run: myt --venv"
        }
        run_cmd "$cmd"
    }
    [ "$ex_code" != 0 ] && {
        error_msg "Failed to build $conf_file - $profile gave error: $ex_code"
    }
    log_it "New tmux conf generated!"

    $use_python_venv && py_venv_deactivate
    if grep -q "Dependency tmux_conf not installed!" "$myt_log"; then
        error_msg "venv seems broken - run: myt --venv"
    elif ! grep -q "Writing tmux" "$myt_log"; then
        error_msg "Python build failed to complete, check: $myt_log"
    fi
}

find_host_profile() {
    # log_it "><> find_host_profile()"
    $tmate_mode && {
        profile="${my_tmux_conf_location}/tmate.py"
        return 0
    }
    #
    #  Step 1 check hardcoded default profile
    #
    profile="${my_tmux_conf_location}/hostnames/_def_profile.py"
    [ -f "$profile" ] && return 0

    #
    #  Hostname profiles are named as lowercased hostname -s with suffix .py
    #
    _p="$(hostname -s | tr '[:upper:]' '[:lower:]').py"

    #
    #  Step 2 check user supplied hostnames folder
    #
    profile="${my_tmux_conf_location}/hostnames/$_p"
    [ -f "$profile" ] && return 0
    #
    #  Step 3 check repo supplied hostnames folder
    #
    profile="${my_tmux_conf_location}/sample_hosts/$_p"
    [ -f "$profile" ] && return 0

    # no hostname based profile found
    profile=""
    return 1
}

tmux_2() {
    # log_it "><> tmux_2()"
    #
    #  Inner tmux server, uses a separate config and prefix
    #
    if [ -z "$profile" ]; then
        profile="$my_tmux_conf_location/t2.py"
    fi

    d_t2="$HOME"/t2
    mkdir -p "$d_t2"

    # shellcheck disable=SC2154
    [ -f "$d_t2"/.tool-versions ] && [ -n "$SSH_CLIENT" ] && {
        # on ssh/mosh machines with a local tmux version, tmux
        # instacraches when anything is selected in tmux if clipboard is not off
        # this is picked up by base.py
        export TMUX_NO_CLIPBOARD=1
    }

    profile="$(realpath "$profile")" # make it survive the cd

    #
    #  run from this location to pick up alternate tmux versions
    #  defined in this location
    #
    cd "$d_t2" || error_msg "Failed to cd into [$d_t2]"
}

#===============================================================
#
#   Main
#
#===============================================================

single_session=true
quick_mode=false
t2_env=false
tmate_mode=false
profile=""
d_initial="$PWD" #  original pwd, will switch back to it before starting tmux

if [ -f "$HOME"/.myt_skip_venv ]; then
    use_python_venv=false
else
    use_python_venv=true
fi

#  Logs how the latest tmux env was setup
myt_log="${TMPDIR:-/tmp}"/myt-"$USER".log

get_my_tmux_conf_location

log_it "=====   starting   ====="
if [ -n "$myt_log" ]; then
    echo "Will log progress to: $myt_log"
    [ -f "$myt_log" ] && rm "$myt_log" # clear log on each run

fi

while [ -n "$1" ]; do
    # log_it "><> processing option: [$1]"
    case "$1" in
    "-h" | "--help") display_help ;;
    "-c")
        shift
        [ -n "$1" ] || {
            error_msg "option -c needs a tmux bin as param"
        }
        tmux_bin="$1"
        ;;
    "-m") tmate_mode=true ;;
    "-q")
        quick_mode=true
        ;;
    "-s") single_session=false ;;
    "--venv")
        log_it "===  Prepare the Python venv for my_tmux_conf"
        py_venv_create
        deactivate
        exit 0
        ;;
    "-2") t2_env=true ;;
    *) profile="$1" ;;
    esac

    shift
done

$quick_mode && [ -n "$profile" ] && error_msg "Can not be combined: -q and $profile"

# [ "$TERM" = "xterm-kitty" ] && {
#     # tmux can't handle this terminal type
#     export TERM="screen-256color"
# }

if $t2_env; then
    tmux_2
else
    [ -n "$profile" ] && {
        [ ! -f "$profile" ] && error_msg "Defined profile not found: $profile"
        # cd will be done when generating the tmux.conf
        # this ensures the path is still valid
        profile="$(realpath "$profile")"
    }
fi

start_tmux
