#!/bin/sh
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#  License: MIT
#
#  Part of https://github.com/jaclu/my_tmux_conf
#
#  Pipe to this in oreder send back data through OSC 52
#
printf "%s" "\033]52;c;$(base64 | tr -d '\r\n')\a"
