#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables
#
# Flake8 also provides: pyflakes, pycodestyle, McCabe
# so it would be redundant to also run them if you use Flake8
#

# Purpose:
#  Lightweight tool for enforcing PEP 8 style guide compliance.
# Strengths:
#  Supports plugins for extended functionality
#  (e.g., flake8-bugbear for additional checks). Less verbose than Pylint.
# Use case:
#  Ideal for enforcing style and detecting common coding issues.

# Installation methods;
#  pip install flake8  # can be installed on iSH
#  brew install flake8
#  (Ubuntu) sudo apt install flake8
#  (Alpine) sudo apk add py3-flake8

# inline-excludes:  # noqa: F841
# project config files: setup.cfg
#  [flake8]
#  max-line-length = 92

if [[ -n "$(command -v ruff)" ]]; then
    #
    # Redundant if ruff is found
    # set to /dev/null instead of "" to avoid warning
    #   missing: plugin_cmd
    #
    proj_plugin_cmd="/dev/null"
else
    proj_plugin_cmd="flake8 --color=always"
fi

plugin_priority=85
