#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

#  Prose linter

# Installation methods;
#  pip install vale
#  brew install vale

plugin_cmd="vale"

# file extensions this plugin handles
plugin_extensions=(
    .md
)

# file-types this plugin handles
plugin_file_types=(
    "UTF-8 Unicode text"*
    "UTF-8 text"
    "Unicode text"
    "ASCII text"*
)
